apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-chatbot
data:
  ALLOWED_ORIGINS: '["http://localhost:3000", "http://127.0.0.1:3000", "http://backend-service:8000", "http://frontend-service:3000"]'
  ENVIRONMENT: "production"
  TIMEOUT_SECONDS: "30"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: todo-chatbot
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vbmVvbmRiX293bmVyOm5wZ192MFJpSVlyTzhqd1NAZXAtZHJ5LWdsaXR0ZXItYTE4MzIxNmUtcG9vbGVyLmFwLXNvdXRoZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbD1yZXF1aXJl
  GEMINI_API_KEY: QUl6YVN5RHhhRi1pRGhrWkRqdm54ZE1KZ3gtZG9MNnIwSDNvM3ZN
  BETTER_AUTH_SECRET: a0w5bU4ycFE1clM4dFUxdlc0eFk3ekEzYkM2ZEU5ZkcyaEo1a004blAxcVI0c1Q3dVYwd1gzeVo2YUI5Y0QyZUY1Z0g4aUoxa0w0bU43b1AwcVIzc1Q2dVY5d1gyeVo1YUI4Y0QxZUY0Z0g3aUowa0wzbU42b1A5cVIyc1Q1dQ==
  JWT_SECRET: a0w5bU4ycFE1clM4dFUxdlc0eFk3ekEzYkM2ZEU5ZkcyaEo1a004blAxcVI0c1Q3dVYwd1gzeVo2YUI5Y0QyZUY1Z0g4aUoxa0w0bU43b1AwcVIzc1Q2dVY5d1gyeVo1YUI4Y0QxZUY0Z0g3aUowa0wzbU42b1A5cVIyc1Q1dQ==
