{{- if .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-ai-chatbot.backend.secret.name" . }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc | quote }}
{{- end }}
---
{{- if .Values.apiKeys.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-ai-chatbot.apikeys.secret.name" . }}
type: Opaque
data:
  openai-api-key: {{ .Values.apiKeys.openaiApiKey | b64enc | quote }}
{{- end }}
---
{{- if .Values.apiKeys.jwtSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-ai-chatbot.auth.secret.name" . }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.apiKeys.jwtSecretKey | b64enc | quote }}
{{- end }}